# Extra autostart processes
exec-once = az login && omarchy-launch-webapp https://outlook.office.com && omarchy-launch-webapp https://teams.cloud.microsoft/ 
exec-once = [workspace 3 ] omarchy-launch-browser
exec-once = [workspace 1 silent] uwsm-app -- spotify
exec-once = [workspace 2 silent] sleep 2 && uwsm-app -- ghostty -e tmux new-session -s GitHub 'bash -i -c "ghdash"' 
