source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = ~/.config/omarchy/current/background
    blur_passes = 0
}

animations {
    enabled = true
}

# image {
#     monitor = eDP-1
#     path = ~/.config/hypr/tux_colored.png
#     size = 120, 120
#     position = 0, -80
#     halign = center
#     valign = center
#     rounding = 0
#     shadow_passes = 0
# }

input-field {
    monitor = eDP-1
    size = 400, 70
    position = 0, 0
    halign = center
    valign = center
    
    dots_size = .2

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 1

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = $TIME12 
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = true
    fingerprint:retry_delay=500
}
